trigger:
  batch: true
  branches:
    include:
      - none

variables:
  # defined in the Pipeline Library variable group
  # see: https://learn.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml
  - group: DEFAULT_VARIABLE_GROUP

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '14.21.3'

  - task: Npm@1
    inputs:
      command: 'ci'

  - script: npm run build:prod

  - task: AzureStaticWebApp@0
    inputs:
      app_location: 'dist/playground-angular'
      config_file_location: 'azure-pipelines/'
      skip_app_build: true
      skip_api_build: true
      is_static_export: true
      azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'
